# This workflow will build a golang project

name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test-amd64:
    name: Build and test (amd64)
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        go: ["1.24"]

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Download packages
        run: |
          go mod download
          make deps

      - name: Build server
        env:
          CGO_ENABLED: 1
          DEBUG: 1
        run: |
          echo "{}" > web/.source-map.json
          make build-server

      - name: Build cli
        env:
          CGO_ENABLED: 0
          GOTAGS: lambda
          DEBUG: 1
        run: make build-cli

      - name: Test
        env:
          CGO_ENABLED: 1
          SHORTTESTS: 1
          DEBUG: 1
        run: make test

  build-and-test-arm64:
    name: Build and test (arm64)
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        go: ["1.24"]

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Download packages
        run: |
          go mod download
          make deps

      - name: Build server
        env:
          CGO_ENABLED: 1
          DEBUG: 1
        run: |
          echo "{}" > web/.source-map.json
          make build-server

      - name: Build cli
        env:
          CGO_ENABLED: 0
          GOTAGS: lambda
          DEBUG: 1
        run: make build-cli

      - name: Test
        env:
          CGO_ENABLED: 1
          SHORTTESTS: 1
          DEBUG: 1
        run: make test
