# This workflow will build a golang project

name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.24"]
        goos: [linux]
        goarch: [amd64]

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Download packages
        run: |
          go mod download
          make deps

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          echo "{}" > web/.source-map.json
          make DEBUG=1 build-server

      - name: Test
        env:
          CGO_ENABLED: 1
          SHORTTESTS: 1
          DEBUG: 1
        run: make test
